= Roadmap

In no particular order:

* <<edn,EDN syntax>>
* <<ctors,ctors>>
** <<entity-tree,entity-tree ctor>>
* <<filters,filters (pull ctor patterns)>>
** <<keys,key filters>>
** <<properties,property filters>>
*** <<inequality,inequalities>>
*** <<equality,equalities>>
*** <<membership,set membership>>
*** <<sorting,sorting>>
* <<mutation,mutation>>
* <<validation,validation>>
** <<values,value types>>
** <<schema,schema support>>
* <<transactions,transactions>>
* <<namespaces,namespaces>>
* <<bulk,bulk operations>>

== [[ed]] EDN syntax

[source,clojure]
----
^{:type IPersistentEntityMap, :migae/keychain [:A/B]} {:a 1}
;; or, minimally:
^{:migae [:A/B]} {:a 1}
----

* enhance ctors/co-ctors to work with edn
* implement edn emitter, e.g. `entity-edn`, `to-edn`, or the like
* do we really need `:migae/keychain`?  isn't `:migae` sufficient?

* do we really need [:type IPersistentEntityMap]?  Maybe not.  We can
  reliably infer type from `:migae` metadata.  For example, from
  `^{:migae [:a/b]}` we infer the additional metadata `:type
  IPersistentEntityMap`; if we later need to support additional migae
  types, we can use `:migae` as namespace, e.g. `:migae/seq` for
  `IPersistentEntityMapSeq`.  On the other hand, we want `type` to
  work for entity-maps in edn.

If we restrict keylinks to a single '/' (i.e. keywords of the form
`:A/B/C` would be disallowed) then we can concatenat keylinks to form
a single symbol, which we could use as a metadata key.  To distinguish
it from ordinary keywords we need to use the `:migae` namespace:

[source,clojure]
----
[:a/b :c/d :e/f] ==>  :migae/a/b/c/d/e/f
(meta ^:migae/a/b/c/d/e/f {:a 1}) => {:migae/a/b/c/d/e/f true}
----


== [[ctors]] ctors

* modal keywords:  `:replace, :transaction, :into, :merge, :conj` etc.
* keyword `:replace` - use `:!' instead?
* pull ctor `entity-map*` - default to homomorphisms, support `:iso` to force isomorphic matches

=== [[entity-tree]] entity-tree ctor

Use case: add a tree of entities, such that parent entity key is
parent key of child.  For example:

[source,clojure]
----
^{:migae/keychain [:Parent/A]} {:a 1}
^{:migae/keychain [:Parent/A Child/A]} {:b 1}
^{:migae/keychain [:Parent/A Child/A Grandchild/A]} {:c 1}
^{:migae/keychain [:Parent/A Child/B]} {:b 2}
^{:migae/keychain [:Parent/A Child/C]} {:b 3}
----

Suppose further that we want to use kinded keys, letting the Datastore
autogen ids for at least some of the parent entities.  In that case we
would have to push the parent, extract its key, and then use that key
to construct the children.  The `entity-tree` constructor will sugar
this; something along the lines of:

[source,clojure]
----
(entity-tree [^{:migae/keychain [:Parent]} {:a 1}
	       [^{:migae/keychain [:Child/A]} {:b 1}
	         [^{:migae/keychain [:Grandchild/A]} {:c 1}
	        ^{:migae/keychain [:Child/B]} {:b 2}
		^{:migae/keychain [:Child/C]} {:b 3}]])
;; or, even sweeter:
(entity-tree [[:Parent] {:a 1}
	       [;; vector of entity-tree nodes
	        [[:Child/A] {:b 1}
	          [[:Grandchild/A] {:c 1}]]
	        [[:Child/B] {:b 2}]
		[[:Child/C] {:b 3}]]])
----

A node in the tree is a vector containing a parent kinded entity-edn
and a vector of child tree nodes.


== [[filters]] filters (pull ctor patterns)

i.e. query filters.

Operators: GAE query filters support `=, not=, >, >=, <, <=,` and
`in`.  We can easily support these using metadata syntax.  For `in`,
use `some`.

=== [[keys]] key filters

E.g. fetch entities with kind :Person whose key is greater than some k K:

[source,java]
----
Filter keyFilter =
  new FilterPredicate(Entity.KEY_RESERVED_PROPERTY,
                      FilterOperator.GREATER_THAN,
                      K)
Query q =  new Query("Person").setFilter(keyFilter);
----

* improper keychain always interpreted as a kind query
* prefix of improper keychain may be: ancestor (default), parent, or part of filter expression

[source,clojure]
----
(entity-map* ^>[:A/B])  ;; entities with key > [:A/B]
(entity-map* ^>[:A/B :Person])  ;; :Person kinded entitys with key > [:A/B]
(entity-map* [:A/B :Person])  ;; default: ancestor query, all :Person ems with ancestor [:A/B]
(entity-map* :parent [:A/B :Person])  ;; parent query: all :Person ems with parent [:A/B]
----

=== [[properties]] property filters

==== [[inequality]] inequality filters

Metadata syntax like `^>{:a 3}` (meaning all :a vals > 3) applies to
the entire map.  But since the datastore restricts inequality filters
to a single property, this is ok.

[source,clojure]
----
(entity-map* k ^>{:a 3}) ;;  #(> % 3) mapped over values of :a
(entity-map* k ^<={:a 9}) ;;  #(<= % 9) mapped over values of :a
(entity-map* k ^some{:a [1 2 3]}) ;; for each :a value v, evaluate `(some [1 2 3] v)`.
----

For multiple filters on one property, we obviously need multiple
specs.  Filters can be combined using `and`, `or`, and `of` (?) so we
need some way to express such combinations as well.

Something like:

[source,clojure]
----
(entity-map* k [^>{:a 3} ^<={:a 9}]) ;; vector means and?
(entity-map* k #{^>{:a 9} ^<={:a 3}}) ;; set means or?
(entity-map* k #{ [^>{:a 3} ^<{:a 9}]
	          [^>{:a 23} ^<{:a 27}]}) ;; (:a > 3 AND :a < 9) OR (:a > 23 AND :a < 27)
;; or, since only one prop allowed, only mention it once:
(entity-map* k {:a #{[^>3 ^<9] [^>23 ^<29]}}) ;; BROKEN - no metadata on numbers!
(entity-map* k {:a #{[> 3 < 9] [> 23 < 29]}}) ;; legal; defaults to inequality query
(entity-map* k ^={:a #{[> 3 < 9] [> 23 < 29]}}) ;; explicit equality filter; see below
----

OOPS!  That won't work - you cannot put metadata on numbers!

Maybe something like `(entity-map* k {:a ^:? #{[> 3 < 9] [> 23 <
29]}})`.  But this is getting pretty unwieldy; maybe a good ol'
keyword like `:filter` is best: `(entity-map* :filter k {:a #{[> 3 < 9] [> 23 <
29]}})`.  But that doesn't resolve the ambiguity.

The problem to be solved here is that we don't have a way to
distinguish this from an exact match filter, which finds entities
whose :a value is exactly `#{[> 3 < 9] [> 23 < 29]}`.  Maybe put some
metadata on the set expression to indicate it is not an equality
filter.  Or, use ^= for equality filters, even though it is not needed
to express the filter logic, only to disambiguate.

==== [[equality]] equality filters

We don't need to use metadata syntax to express equality filters; we
can just specify the maps.  However, in order to distinguish equality
from inequality filters, we need to mark everything explicitly.

[source,clojure]
----
(entity-map* k ^={:a 1}) ;; homomorphisms: entities containing [:a 1] entry
(entity-map* :iso k ^={:a 1}) ;; isomorphisms: entities matching {:a 1} exactly
;; or
(entity-map* k ^=={:a 1}) ;; `==` means isomorphism: entities matching {:a 1} exactly
----

Equality filters on multiple fields are allowed, so in this case we
may need to mention each field explicitly.

==== [[membership]] set membership

For the Datastore IN filter we use `clojure.core/some`:

[source,clojure]
----
(entity-map* k ^some{:a [1 2 3]}) ;; for each :a value v, evaluate `(some [1 2 3] v)`.
----

==== [[sorting]] sorting

Vector.  `:sort [:a :b]`

Default is ascending order: just the field key.  For descending, add a negative:  `:sort [:-a :-b]`


=== rejected syntax

The problem with using functions is that we cannot validate them.  A
  function can express any predicate but we need to be able to extract
  a valid filter for querying against the datastore before we can
  apply the full predicate.  So we need to either quote the form or
  implement a macro of some kind:

[source,clojure]
----
(entity-map* k {:a #(> % 1)}) ;; value at :a > 1
(entity-map* k {:a '(> % 1)})
(entity-map* k {:a (migae-filter >  1)}) ;; yech
(entity-map* k {:a '(odd? %)}) ;; convert to: fetch all, then filter with #(odd %)
----

What about, e.g. all odd values between m and n?  We need a syntactic
means of marking the expression to be used as a property filter.  Use metadata?

[source,clojure]
----
(entity-map* k ^{:filter '>}[:a 3])
(entity-map* k '(odd? ^>{:a 3})) ;; ????
----

With `^>{:a 3}` we can check metadata to find the "basic" filter
predicate to use in querying the datastore.  In the above example, run
the filter to get a list of results, then map over them with odd?

===== older rejects

    ;;  (:: (:a = 1 & :b > 2) | (:a < 5))

;; better: use a reader to mimic function
;;     (ds/emaps?? [:A] {:a #migae/fn (= % 2)})
;; or: (ds/emaps?? [:A] {:a '(= % 2)})

    (let [ems (ds/emaps?? [:A] {:a '(= 2)})]
    ;; (let [ems (ds/emaps?? [:A] (& :a = 1 ;  and
    ;;                               :b = 2))
    ;;       ems2 (ds/emaps?? [:A] (| :a = 1 ; or
    ;;                                :b = 2))]

== [[mutation]] mutation

* support mode tags :into, :merge, etc.

* modal decorators: `+` and `-`.  default for e.g. `:into` is to
  overwrite old values; modal decorators allow us to modify this
  behavior. So `:into+` means 'augment' (e.g. cons, convert to list if
  necessary), and `:into-` means discard new val if an old val exists.

[source,clojure]
----
(def em (entity-map! [:A/B] {:a 1}))
(entity-map! :into [:A/B] {:x 9}) ;; => {:a 1, :x 9} saved to [:A/B] entity
(entity-map! :into em {:x 9}) ;; same
(entity-map! :into [:A/B] {:a 9}) ;; => update: {:a 9} saved to [:A/B] entity
(entity-map! :augment [:A/B] {:a 9}) ;; => augment: {:a [1 9]} saved to [:A/B] entity
;; or add a modal decorator:
(entity-map! :into+ [:A/B] {:a 9}) ;; => augment: {:a [1 9]} saved to [:A/B] entity
(entity-map! :into+ (entity-map [:A/B] {:a 1}) {:a 9}) ;; => [:A/B] {:a [1 9]}
(entity-map! :into- [:A/B] {:a 9}) ;; => discard 9, since {:a 1} already exists
;; or
(entity-map! :into? [:A/B] {:a 9}) ;; => if :a exists ('?') discard new val 9
(entity-map! :replace :into [:A/B] {:x 9}) ;; avoid EntityNotFoundException
(entity-map! :transaction :into [:A/B] {:x 9}) ;;
----

* do we need bangified ops :into!, :merge! etc.?

* by default `into` overwrites existing values.  what if we want to
 preserve them?  then we have two options:

** discard the new value and keep the old
** keep both - make a list value of the old and new vals.  syntax: `:augment`, or modal decorator `+`

== [[validation]] validation

=== [[values]] value types

=== [[schema]] schema support

* associate e.g. Prismatic schema specification with kind keyword
* postfix '?' on kind keyword means "validate against schema"; e.g.
* ctor mode keyword `:iso` checks for isomorphism against schema; default is homomorphism

[source,clojure]
----
(entity-map [:A?/B] {:x 9}) ;; validate {:x 9} against :A schema
----

== [[transactions]] Transactions

* `with-transaction`
* ctor mode key `:transaction`

== [[namespaces]] GAE Namespaces

== [[bulk]] bulk operations

=== bulk loading

* link:http://ikaisays.com/2010/08/11/using-the-app-engine-mapper-for-bulk-data-import/[Using the App Engine Mapper for bulk data import] (somewhat outdated)

edn: to add records, we can just upload a file of edn representations of entity-maps.

=== bulk update

* investigate link:https://cloud.google.com/appengine/docs/java/dataprocessing/[MapReduce for AppEngine]

Case: add a field `:foo` with default value `:bar` to all entities of
kind `:k`.  Something like:

[source,clojure]
----
(let [ems (ds/entity-map* [:k])]
     (doseq [grp grps]
     	    (ds/entity-map! :into grp {:foo :bar})))
----

